/**
 * SStore Admin API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export interface ApiOrdersShoppingCartStoreProductVariant {
    id?: number;

    price?: string;

    inStock?: number;

    storeId?: number;

    productId?: number;

    productVariantId?: number;

    devices?: Array<models.ApiOrdersShoppingCartStoreProductVariantDevices>;

    shoppingCartDetails?: Array<models.ShoppingCartDetails>;

    product?: models.ApiOrdersShoppingCartStoreProductVariantProduct;

    productVariant?: models.ApiOrdersShoppingCartStoreProductVariantProductVariant;

    store?: models.ApiOrdersShoppingCartStoreProductVariantStore;

}
