/**
 * SStore Admin API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export interface ApiOrdersShoppingCartUserUserReview {
    id?: number;

    liked?: boolean;

    userId?: number;

    reviewId?: number;

    review?: models.Reviews;

    user?: models.Users;

}
