/**
 * SStore Admin API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export interface Orders1 {
    id?: number;

    code?: string;

    rating?: number;

    comment?: string;

    state?: number;

    createdAt?: Date;

    updatedAt?: Date;

    shoppingCartId?: number;

    invoices?: Array<models.ApiOrdersInvoices>;

    shoppingCart?: models.ApiOrdersShoppingCart;

}
