/**
 * SStore Admin API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export interface Products1 {
    id?: number;

    name?: string;

    barcode?: string;

    description?: string;

    imgUrl?: string;

    createdAt?: Date;

    updatedAt?: Date;

    categoryId?: number;

    productTypeId?: number;

    customAttributes?: Array<models.ApiOrdersShoppingCartStoreProductVariantProductCustomAttributes>;

    productTypeAttributeValues?: Array<models.ApiOrdersShoppingCartStoreProductVariantProductProductTypeAttributeValues>;

    reviews?: Array<models.Reviews>;

    storeProductVariant?: Array<models.StoreProductVariant>;

    category?: models.ApiOrdersShoppingCartStoreProductVariantProductCategory;

    productType?: models.ApiOrdersShoppingCartStoreProductVariantProductProductType;

}
