/**
 * SStore Admin API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export interface Users {
    id?: number;

    fullName?: string;

    dob?: Date;

    tel?: string;

    address?: string;

    email?: string;

    gender?: number;

    avatar?: string;

    createdAt?: Date;

    updatedAt?: Date;

    accounts?: Array<models.ApiOrdersShoppingCartUserAccounts>;

    reviews?: Array<models.ApiOrdersShoppingCartUserReviews>;

    shoppingCarts?: Array<models.ShoppingCarts>;

    stores?: Array<models.ApiOrdersShoppingCartStoreProductVariantStore>;

    userReview?: Array<models.ApiOrdersShoppingCartUserUserReview>;

}
